In [15]:
import numpy as np
import numexpr as ne
from tqdm import tqdm

In [4]:
X = np.array([-1.50, -1.00, -0.75, -0.40, -0.25, 0.00])


In [11]:
X = X.reshape(-1,1)

In [12]:
def rbf_kernel(X):
    X_norm = np.sum(X ** 2, axis = -1)
    var = 5
    gamma = 0.01
    K = ne.evaluate('v * exp(-g * (A + B - 2 * C))', {
        'A' : X_norm[:,None],
        'B' : X_norm[None,:],
        'C' : np.dot(X, X.T),
        'g' : gamma,
        'v' : var
    })
    return K

In [13]:
rbf_kernel(X)

array([[5.        , 4.98751561, 4.97195395, 4.93986455, 4.92248219,
        4.88875619],
       [4.98751561, 5.        , 4.99687598, 4.98203236, 4.97195395,
        4.95024917],
       [4.97195395, 4.99687598, 5.        , 4.99387875, 4.98751561,
        4.97195395],
       [4.93986455, 4.98203236, 4.99387875, 5.        , 4.99887513,
        4.9920064 ],
       [4.92248219, 4.97195395, 4.98751561, 4.99887513, 5.        ,
        4.99687598],
       [4.88875619, 4.95024917, 4.97195395, 4.9920064 , 4.99687598,
        5.        ]])

In [19]:
def kernel(X,Y,gamma=0.5):
    K = np.zeros((X.shape[0], Y.shape[0]))
    for idx, x in tqdm(enumerate(X)):
             for jdx, y in enumerate(Y):
                 K[idx, jdx] = np.exp(-gamma * np.linalg.norm(x - y) ** 2)
    return K

In [33]:
k = kernel(X,X)

6it [00:00, 6006.16it/s]


In [35]:
k

array([[1.        , 0.8824969 , 0.7548396 , 0.54607443, 0.45783336,
        0.32465247],
       [0.8824969 , 1.        , 0.96923323, 0.83527021, 0.7548396 ,
        0.60653066],
       [0.7548396 , 0.96923323, 1.        , 0.94058806, 0.8824969 ,
        0.7548396 ],
       [0.54607443, 0.83527021, 0.94058806, 1.        , 0.98881304,
        0.92311635],
       [0.45783336, 0.7548396 , 0.8824969 , 0.98881304, 1.        ,
        0.96923323],
       [0.32465247, 0.60653066, 0.7548396 , 0.92311635, 0.96923323,
        1.        ]])

In [24]:
x_s = np.array([0.2])


In [26]:
x_s.reshape(-1,1)

array([[0.2]])

In [27]:
k_s = kernel(x_s,X)

1it [00:00, 1001.74it/s]


In [28]:
k_s

array([[0.23574608, 0.48675226, 0.63683161, 0.83527021, 0.90370708,
        0.98019867]])

In [29]:
k_ss = kernel(x_s,x_s)

1it [00:00, 1001.27it/s]


In [30]:
k_ss

array([[1.]])

In [31]:
y = np.array([-1.75,-1.1,-0.4,0.2,0.4,0.7]).reshape(-1,1)

In [32]:
y

array([[-1.75],
       [-1.1 ],
       [-0.4 ],
       [ 0.2 ],
       [ 0.4 ],
       [ 0.7 ]])

In [55]:
y_pred = k_s.dot(np.linalg.inv(k)).dot(y)

In [49]:
k_s.shape

(1, 6)

In [50]:
np.linalg.inv(k).shape

(6, 6)

In [45]:
y.shape

(6, 1)

In [57]:
y_pred

array([[0.74635119]])

In [63]:
variance = k_ss - k_s.dot(np.linalg.inv(k)).dot(k_s.T)

In [64]:
variance

array([[8.30989087e-06]])

In [62]:
k_s.dot(np.linalg.inv(k)).dot(k_s.T)

array([[0.99999169]])