In [1]:
import numpy as np
import numexpr as ne
from numpy import genfromtxt



In [2]:
data = np.genfromtxt('bank.csv', delimiter=',', skip_header=True)
data = np.delete(data,0,1)
X = data[:,[0,1,2,3,4,5,6,7,9,10,11,12]]

In [20]:
X_norm = np.sum(X ** 2, axis = -1)
var = 5
gamma = 0.01
K = ne.evaluate('v * exp(-g * (A + B - 2 * C))', {
        'A' : X_norm[:,None],
        'B' : X_norm[None,:],
        'C' : np.dot(X, X.T),
        'g' : gamma,
        'v' : var
})

In [21]:
K


array([[5.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 5.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 8.21506436e-18, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 5.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        5.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 8.21506436e-18, 0.00000000e+00, ...,
        0.00000000e+00, 5.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 5.00000000e+00]])

In [22]:
from sklearn.metrics.pairwise import rbf_kernel

K_1 = var * rbf_kernel(X, gamma = gamma)

In [23]:
K_1


array([[5.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 5.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 8.21506436e-18, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 5.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        5.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 8.21506436e-18, 0.00000000e+00, ...,
        0.00000000e+00, 5.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 5.00000000e+00]])

In [18]:
def gram_matrix(X, Y, gamma=0.5):
    K = np.zeros((X.shape[0], Y.shape[0]))
    for i, x in tqdm(enumerate(X)):
            for j, y in enumerate(Y):
                K[i, j] = var * np.exp(-gamma * np.linalg.norm(x - y) ** 2)
        
    return K

In [19]:
gram_matrix(X,X, gamma=0.01)

5000it [04:57, 16.78it/s]


array([[5.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 5.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 8.21506436e-18, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 5.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        5.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 8.21506436e-18, 0.00000000e+00, ...,
        0.00000000e+00, 5.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 5.00000000e+00]])

In [17]:
from tqdm import tqdm 
